---
title : panic
---

## panic! 宏

当我们在 rust 中遇到无法处理的异常时，程序会 `panic` 退出（因为恐慌而崩溃：D）。但我们也可以通过 `panic!` 宏主动让程序 panic .

```rust
fn main() {
    panic!("crash and burn");
}
```

`panic!` 宏让我们在遇到一个可能失败的操作时通过 `match` 处理两种情况：操作成功与操作失败。

比如当我们打开一个文件时，如果成功，我们想要获取这个文件的信息并继续执行，若失败，则 `panic` 退出程序：

```rust
use std::fs::File;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {:?}", error),
    };
}
```

`File::open` 会返回一个 `Result<T,E>` 类型到 `greeting_file_result`，我们可以通过 `match` 来匹配 `Result` 的两种枚举值来进行不同的处理。

这种场景十分普遍，因此除了直接用 `match` 和 `panic!`，rust 为我们提供了一些辅助方法： `unwrap` 、 `expect` 与 `?` .

## unwrap 与 expect

```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt").unwrap();
}
```

`unwrap` 直译为 “无法包裹” ，如果 `Result` 返回 `Err` 类型，则它不在程序所能处理的范围能，因此自动 panic 退出程序。

而 `expect` 和 `unwrap` 十分类似，它允许我们在 `panic` 时自定义一些信息：

```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt")
        .expect("hello.txt should be included in this project");
}
```

## ?

在编写程序时，我们常常不希望直接 `panic` 退出程序，而是返回一个错误类型给调用者，让上级程序决定如何处理这个错误：

```rust
#![allow(unused)]
fn main() {
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}
}
```

在这个例子中， `read_username_from_file` 可能返回从文件中读出的 `String` 值，也可能在打开文件和读出数据时发生错误，错误类型均为 `io:Error` .

而 `?` 在与 `unwrap` 与 `expect` 相同，会自动让程序 `panic` 外，还会查看是否方法有指定返回的错误类型，如果有，则**尝试将当前错误转换为方法制定的错误类型返回**。比如：

```rust
fu test()->Result<String , MyError>{
  let a = fn1()?
}
```

若 fn 成功，则正常返回 fn 抛出的值给 a，若 fn 失败，则**尝试转换**为`MyError` 类型并调用 panic!


使用 `?` 可以简写上面的一大串代码：

```rust
#![allow(unused)]
fn main() {
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
}
```

因为当 `?` 前面的语句成功时，会返回成功的结果，因此我们可以像这样进行链式调用：

```rust
#![allow(unused)]
fn main() {
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();

    File::open("hello.txt")?.read_to_string(&mut username)?;

    Ok(username) // Ok(String) 是为了返回一个 Result
}
}
```

我们刚才用 `?` 帮我们自动返回一个 `Result` 类型的变量，事实上， `?` 还能够自动返回一个 `Option` 类型的变量，比如：

```rust
fn last_char_of_first_line(text: &str) -> Option<char> {
    text.lines().next()?.chars().last()
}
```

如果text没有第一行，则返回 `Option<char>` 的 `null` 枚举值，如果有，则将下一行转换为字符，并取最后一个字符返回 `Option<char>` 的 `Some` 枚举值。